language: python
python:
  - "3.4"

services:
  - mysql
  - git

before_install:
  - mysql -e "CREATE DATABASE oj;"
  - mysql oj -e "CREATE USER 'oj'@'%' IDENTIFIED BY 'RESET_BY_YOUR_OWN';"
  - git clone https://github.com/lodevil/Lo-runner.git
  - cd Lo-runner && ./setup.py

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python3 manage.py test

# after_success: 
#   - bash <(curl -s https://codecov.io/bash)